collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  auto_id_prefix: false,
  auto_id_stripping: false
  auto_ids: true
  entity_output: as_char
  footnote_backlink_inline: false
  footnote_nr: 1
  hard_wrap: false
  header_offset: 0
  html_to_native: false
  input: GFM
  line_width: 72
  parse_block_html: false
  parse_span_html: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  show_warnings: false

incremental: true